voxel:
  x_min: -50
  x_max: 50
  y_min: -50
  y_max: 50
  z_min: -5
  z_max: 3
  voxel_x: 0.25
  voxel_y: 0.25
  max_points_per_pillar: 100
  max_pillars: 12000

model:
  num_classes: 1   # car only (demo)
